# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version       = 1.21.1
yarn_mappings           = 1.21.1+build.3
fabric_loader_version   = 0.16.10
neoforge_version        = 21.1.121
enabled_platforms       = fabric,neoforge

# Mod Properties
mod_version 			= 9.0.0
maven_group 			= hunternif.mc.atlas
archives_base_name 		= antiqueatlas

# Dependencies
architectury_version    = 13.0.8
cloth_config_version	= 15.0.140
fabric_api_version      = 0.115.0+1.21.1
mod_menu_version		= 11.0.3

# Publishing
curseforge_id           = 227795
modrinth_id             = wHODup9j